# .tarpaulin.toml
[report]
ignore-tests = true

# Exclure les sources legacy et spécifiques plateforme
exclude-files = [
  "src/main.rs",
  "src/storage.rs",
  "src/crypto/*.rs",
  "miaou-core/src/mobile.rs",
]

# Si tu veux aussi ignorer les benches dans la métrique
# (ils gonflent parfois le dénominateur)
# exclude-files = ["benches/**"]