[package]
name = "miaou"
version = "0.1.0"
edition = "2021"
authors = ["yrbane <yrbane@nethttp.net>"]
description = "Plateforme de communication décentralisée et sécurisée"
repository = "https://github.com/yrbane/miaou"
license = "MIT OR Apache-2.0"
keywords = ["p2p", "encryption", "communication", "decentralized"]
categories = ["network-programming", "cryptography"]

[lib]
name = "miaou"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "miaou-cli"
path = "src/bin/cli.rs"

[dependencies]
# Stack cryptographique cohérente (Option A : RustCrypto + Dalek)
# AEAD avec XChaCha20 (nonces 192-bit, moins de contraintes d'unicité)
chacha20poly1305 = { version = "0.10", default-features = false, features = ["alloc"] }

# Signatures et ECDH via Dalek (performance + audit)
ed25519-dalek = { version = "2", features = ["rand_core", "zeroize"] }
x25519-dalek = { version = "2", features = ["static_secrets"] }

# KDF et hachage
hkdf = "0.12"
blake3 = { version = "1", features = ["zeroize"] }
sha3 = "0.10"
argon2 = "0.5"

# Transport sécurisé (mis à jour)
rustls = { version = "0.23", default-features = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }

# Sécurité et gestion des secrets
zeroize = "1.7"
subtle = "2.5"
secrecy = "0.8"
rand_core = { version = "0.6", features = ["getrandom"] }
thiserror = "1"

# Sérialisation et utilitaires
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"

# CLI
clap = { version = "4.5", features = ["derive"] }
rpassword = "7.3"
anyhow = "1.0"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
android_logger = "0.13"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"

[features]
default = ["desktop"]
desktop = []
mobile = []
android = ["mobile"]
ios = ["mobile"]
wasm = []

[package.metadata.android]
package = "net.nethttp.miaou"
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi", "i686-linux-android", "x86_64-linux-android"]

[package.metadata.bundle]
name = "Miaou"
identifier = "net.nethttp.miaou"
version = "0.1.0"
copyright = "Copyright (c) yrbane 2024"
category = "social-networking"
short_description = "Communication décentralisée"
long_description = "Plateforme de communication peer-to-peer sécurisée et décentralisée"

# Tests et dev
[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.5"


[[bench]]
name = "crypto_benchmarks"
harness = false
