# Configuration pour cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

[licenses]
# Liste des licences acceptées
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
copyleft = "warn"
unlicensed = "deny"
confidence-threshold = 0.8

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = []