# Configuration pour cargo-mutants
# Tests de mutation pour Miaou v0.1.0

[mutants]
# Timeout pour chaque test de mutation
timeout = 60

# Dossiers et fichiers à examiner
examine_paths = [
    "miaou-crypto/src/",
    "miaou-core/src/",
    "miaou-cli/src/main.rs"
]

# Exclusions pour éviter les faux positifs
exclude_globs = [
    "**/tests/**",
    "**/benches/**",
    "**/target/**"
]

# Types de mutations à appliquer
mutations = [
    "replace_binary_operator",
    "replace_unary_operator", 
    "replace_literal",
    "replace_comparison",
    "negate_condition"
]

# Seuil minimum de détection des mutants
minimum_test_timeout = 10

# Configuration spécifique crypto (plus conservatrice)
[[mutants.skip]]
# Éviter les mutations sur les constantes cryptographiques critiques
glob = "miaou-crypto/src/constants.rs"
reason = "Constantes cryptographiques sensibles"

[[mutants.skip]]
# Éviter les mutations sur la zeroization
glob = "**/zeroize*.rs"
reason = "Sécurité mémoire critique"