[target.x86_64-linux-android]
ar = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang"

[target.aarch64-linux-android]
ar = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
ar = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
ar = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/seb/.android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang"