name: Security Audit

on:
  schedule:
    # Run security audit weekly on Sundays at 02:00 UTC
    - cron: '0 2 * * 0'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-audit-
            ${{ runner.os }}-cargo-
      
      - name: Run security audit
        run: cargo audit --deny warnings
      
      - name: Run dependency vulnerability scan
        run: cargo audit --json --quiet | jq -r '.vulnerabilities[] | "⚠️  \(.package.name) \(.package.version): \(.advisory.title)"' || true